name: odc_hackathon_web_project
description: A new Flutter project.


publish_to:




version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"


dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.2
  change_app_package_name: ^0.1.3
  bloc: ^8.0.3
  flutter_bloc: ^8.0.1
  http: ^0.13.4
  auto_size_text: ^3.0.0
  modal_progress_hud_nsn:
  shared_preferences: ^2.0.15
  fluttertoast: ^8.0.9
  font_awesome_flutter: ^10.1.0
  flutter_svg: ^1.0.3
  dio: ^4.0.6
  form_field_validator: ^1.1.0
  google_fonts: ^3.0.1
  mouse_parallax: ^1.1.0
  equatable:
  sprung:
  go_router: ^4.2.0
  html: ^0.15.0
  google_sign_in: ^5.4.0
  image_picker: ^0.8.5+3
  mime: ^1.0.2
  flutter_staggered_grid_view: ^0.4.0
  carousel_slider: ^4.1.1
  flutter_web_auth: ^0.4.1
#  geolocator: ^9.0.1


dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0




flutter:


  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
